server:
  servlet:
    context-path: /idispatch

vaadin:
  whitelisted-packages: net.pkhapps, com.vaadin
  exclude-urls: /rest/**
  frontend:
    hotdeploy: false

spring:
  jpa:
    open-in-view: false

management:
  server:
    port: 8081

logging:
  level:
    net.pkhapps: debug
    org.springframework.security: debug

