server:
  servlet:
    context-path: /idispatch

vaadin:
  exclude-urls: /rest/**
  frontend:
    hotdeploy: false
  allowed-packages: net.pkhapps, com.vaadin

spring:
  jpa:
    open-in-view: false

logging:
  level:
    net.pkhapps: debug
    org.springframework.security: debug
